services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: GameEnjoyer2026!
      POSTGRES_USER: adamskri
      POSTGRES_DB: adamskri
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
