SET search_path TO orders_db_ka;
-- Query Problems

    -- Easy:

-- 1. Select user id, email and order id for each order for all registered users. 
--    Order by the order id DESC. A registered user is a user that exists in the users table. 
--    A non-registered user will appear as a null value for user_id in the orders table.
SELECT user_id, users.email, orders.id 
FROM orders 
    INNER JOIN users ON orders.user_id = users.id 
ORDER BY orders.id DESC;

-- 2. Select the email of users who have contents in their bags. Order by the user id ASC.
SELECT email 
FROM users WHERE id IN (SELECT user_id FROM bag_contents) ORDER BY id ASC;


    -- Medium:

-- 1. Select the item type and the number of unique items for each item type. Order by the id of the item type.
SELECT item_type_id, COUNT(DISTINCT id) 
FROM items 
GROUP BY item_type_id 
ORDER BY item_type_id;

-- 2. Select the email and the number of orders for each user's email address. Consider all non-registered users as one entry. 
--    Order by the number of orders DESC.
SELECT users.email, COUNT(orders.id) 
FROM orders 
    LEFT JOIN users ON orders.user_id = users.id 
GROUP BY users.email 
ORDER BY COUNT(orders.id) DESC;


    -- Hard:

-- 1. Select all order information where the order cost is not equal to the sum of the
--    order contents cost associated with that order. Order by order id ASC.
SELECT * FROM orders WHERE cost != (
    SELECT SUM(items.price * order_contents.quantity) 
    FROM order_contents 
INNER JOIN items ON order_contents.item_id = items.id 
    WHERE order_contents.order_id = orders.id) 
ORDER BY id ASC;

-- 2. Select all registered users id's and emails for users who have purchased an
--    order with more than one quantity of an item. Order by the user id ASC.
SELECT id, email FROM users WHERE id in (
    SELECT user_id FROM orders
    WHERE id IN (
        SELECT order_id FROM order_contents
        WHERE quantity > 1
    )
)
ORDER BY id ASC;



-- View Problems

-- 1. Write SQL commands to create a view with queries corresponding to the Medium-2 problem above.
CREATE VIEW users_with_orders AS
SELECT users.email, COUNT(orders.id) AS order_count
FROM orders 
    LEFT JOIN users ON orders.user_id = users.id AND users.email IS NOT NULL
GROUP BY users.email 
ORDER BY COUNT(orders.id) DESC;

-- 2. Write SQL command to grant read privilege to one of your classmates on the view.
GRANT SELECT ON users_with_orders TO mallandj;



-- Stored Procedure Problems

-- 1. Write a stored procedure that takes item_type_name as a parameter and inserts
--    a row in the item_types table. The next value for the id column will be read from
--    the system and other column values will be generated by the stored procedure.
--    Using this stored procedure three times, insert three item types into the table

CREATE OR REPLACE PROCEDURE insert_item_type(p_item_type_name varchar)
AS $proc$
BEGIN
  INSERT INTO item_types(item_type_name) VALUES(p_item_type_name);
END;
$proc$ LANGUAGE plpgsql;

CALL insert_item_type('Jackets');
CALL insert_item_type('Scarves');
CALL insert_item_type('Sunglasses');


--  2. Write a function with a cursor that runs a query to select the item name, item
--     price and the number of items in stock for each item that has stock available. The
--     function will read the results from the cursor and will construct a text that will print
--     out the results record by record in separate lines

CREATE OR REPLACE FUNCTION print_in_stock()
RETURNS TEXT
LANGUAGE PLPGSQL
AS $proc$
DECLARE
    item_data RECORD;
    result TEXT DEFAULT '';
    items_cursor CURSOR FOR 
        SELECT item_name, price, item_stock.number_in_stock
        FROM items
        INNER JOIN item_stock ON items.id = item_stock.item_id
        WHERE item_stock.number_in_stock > 0;
BEGIN
    OPEN items_cursor;
    LOOP
        FETCH items_cursor INTO item_data;
        EXIT WHEN NOT FOUND;
        result := result || 'Item Name: ' || item_data.item_name || ', Price: ' || item_data.price || ', Stock: ' || item_data.number_in_stock || E'\n';
    END LOOP;
    CLOSE items_cursor;
    RETURN result;
END
$proc$ ;

SELECT print_in_stock();

--  3. Create a trigger and associated trigger function that will change the value of
--     column “deleted” to TRUE when a row in the items table is deleted. The delete
--     operation will not physically delete the row, rather will change value of “deleted”
--     column to TRUE.

CREATE OR REPLACE FUNCTION mark_delete()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $proc$
BEGIN
    UPDATE items SET deleted = TRUE WHERE id = OLD.id;
    RETURN NULL;
END;
$proc$;


-- Create the trigger when a delete occurs on the items table.
CREATE TRIGGER mark_delete_trigger
BEFORE DELETE ON items
FOR EACH ROW
EXECUTE FUNCTION mark_delete();

DELETE FROM items WHERE id = 1;
SELECT * FROM items WHERE id = 1;
