-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS assignment_2.game_results
(
    season_number integer,
    game_id serial,
    game_number integer,
    winning_team_name character varying(255),
    team_current_name character varying(255),
    team_current_location character varying(255),
    points_scored character varying(255),
    PRIMARY KEY (game_id),
    UNIQUE (winning_team_name),
    UNIQUE (season_number),
    UNIQUE (game_number),
    UNIQUE (team_current_name),
    UNIQUE (team_current_location)
);

CREATE TABLE IF NOT EXISTS assignment_2.season_info
(
    season_id serial,
    season_year integer,
    game_year integer,
    game_number integer,
    PRIMARY KEY (season_id),
    UNIQUE (game_number)
);

CREATE TABLE IF NOT EXISTS assignment_2.player_info
(
    player_id serial,
    player_name character varying(255),
    "position" character varying(255),
    team_current_name character varying(255),
    team_current_location character varying(255),
    PRIMARY KEY (player_id),
    UNIQUE (team_current_name),
    UNIQUE (team_current_location)
);

CREATE TABLE IF NOT EXISTS assignment_1.team_info
(
    team_id serial,
    team_name character varying,
    team_location character varying,
    PRIMARY KEY (team_id)
);

ALTER TABLE IF EXISTS assignment_2.game_results
    ADD FOREIGN KEY (winning_team_name)
    REFERENCES assignment_1.team_info (team_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS assignment_2.game_results
    ADD FOREIGN KEY (season_number)
    REFERENCES assignment_2.season_info (season_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS assignment_2.player_info
    ADD FOREIGN KEY (team_current_name)
    REFERENCES assignment_1.team_info (team_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS assignment_2.player_info
    ADD FOREIGN KEY (team_current_location)
    REFERENCES assignment_1.team_info (team_location) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;